apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocktracker-pods
spec:
  replicas: 5
  selector:
    matchLabels:
        app: stocktrackerapp
  template:
    metadata:
      labels:
        app: stocktrackerapp
    spec:
      containers:
        - name: stocktrackerapp-ctr
          image: nezraal/net6repo:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
